"""Write the Beads treatment of the SELFTAC halves into both websites' SELFTAC diagram.

Each half (warhead or E3 ligand plus its half of the linker) is drawn about its own centre
so the scroll code can move the halves independently. Placed at the offset HALF_DX/HALF_DY
(scaled), the two halves sit exactly as in the joined molecule. The script replaces the
markup between the selftac-halves markers and the HALF_DX/HALF_DY constants in each site.
"""
import json, os, re

D = os.path.dirname(os.path.abspath(__file__)) + '/'
SITES = [D + '../index.html', D + '../editorial/index.html']
d = json.load(open(D + 'mz1_2d.json'))
A, EL, PART, BONDS, PATH, BRK = d['atoms'], d['el'], d['part'], d['bonds'], d['linker_path'], d['break']
MID = PATH.index(BRK[1])
K = 4.0  # px per angstrom at scale 1
STRETCH = 3.5  # extra angstroms of linker per side, to give the linker more presence at diagram size
nbrs = {i: [] for i in range(len(A))}
for i, j, o in BONDS:
    nbrs[i].append(j); nbrs[j].append(i)

def f(v): return f'{v:.1f}'

def closed(q):  # closed Catmull-Rom
    n = len(q); out = f'M{f(q[0][0])} {f(q[0][1])}'
    for k in range(n):
        p0, p1, p2, p3 = q[k - 1], q[k], q[(k + 1) % n], q[(k + 2) % n]
        out += f'C{f(p1[0] + (p2[0] - p0[0]) / 6)} {f(p1[1] + (p2[1] - p0[1]) / 6)} {f(p2[0] - (p3[0] - p1[0]) / 6)} {f(p2[1] - (p3[1] - p1[1]) / 6)} {f(p2[0])} {f(p2[1])}'
    return out + 'Z'

def opened(q):  # open Catmull-Rom
    n = len(q); out = f'M{f(q[0][0])} {f(q[0][1])}'
    for k in range(n - 1):
        p0, p1, p2, p3 = q[max(k - 1, 0)], q[k], q[k + 1], q[min(k + 2, n - 1)]
        out += f'C{f(p1[0] + (p2[0] - p0[0]) / 6)} {f(p1[1] + (p2[1] - p0[1]) / 6)} {f(p2[0] - (p3[0] - p1[0]) / 6)} {f(p2[1] - (p3[1] - p1[1]) / 6)} {f(p2[0])} {f(p2[1])}'
    return out


def stretch(p, s, i=None):
    """Push each head outward along x; linker atoms move in proportion to their distance from the break."""
    if i is not None and i in PATH:
        t = abs(PATH.index(i) - (MID - .5)) / (MID - .5 if s == 'L' else len(PATH) - MID - .5)
    else:
        t = 1
    return [p[0] + (-1 if s == 'L' else 1) * STRETCH * min(t, 1), p[1]]

halves = {}
for part, s in (('warhead', 'L'), ('e3lig', 'R')):
    head = [n for n in nbrs[PATH[0] if s == 'L' else PATH[-1]] if PART[n] == part][0]
    chain = [head] + PATH[:MID] if s == 'L' else PATH[MID:] + [head]
    blob = {k: [stretch(p, s) for p in d[k][part]] for k in ('blob_soft', 'blob', 'blob_core')}
    at = {i: stretch(A[i], s, i) for i in chain}
    pts = blob['blob_soft'] + list(at.values())
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    c = ((min(xs) + max(xs)) / 2, (min(ys) + max(ys)) / 2)
    T = lambda p: [(p[0] - c[0]) * K, (p[1] - c[1]) * K]
    g = (f'<path class="bz-s" d="{closed([T(p) for p in blob["blob_soft"]])}"/>'
         f'<path class="bz-o" d="{closed([T(p) for p in blob["blob"]])}"/>'
         f'<path class="bz-c" d="{closed([T(p) for p in blob["blob_core"]])}"/>'
         f'<path class="bz-ln" d="{opened([T(at[i]) for i in chain])}"/>')
    for i in chain[1:] if s == 'L' else chain[:-1]:
        x, y = T(at[i])
        cls = 'bz-x' if i in BRK else 'bz-ox' if EL[i] == 'O' else 'bz-b'
        g += f'<circle class="{cls}" cx="{f(x)}" cy="{f(y)}" r="{3 if i in BRK else 2.5 if EL[i] == "O" else 1.9}"/>'
    halves[s] = (c, g)

dx = (halves['R'][0][0] - halves['L'][0][0]) * K
dy = (halves['R'][0][1] - halves['L'][0][1]) * K
markup = ('<!-- selftac-halves:start (generated by molecule/gen_site_icon.py) -->\n'
          f'          <g id="halfA" class="fl hz-a" style="--fa:1.5px;--fd:-1.2s">{halves["L"][1]}</g>\n'
          f'          <g id="halfB" class="fl hz-b" style="--fa:1.5px;--fd:-3.1s">{halves["R"][1]}</g>\n'
          '          <!-- selftac-halves:end -->')
for path in SITES:
    src = open(path).read()
    src, n1 = re.subn(r'<!-- selftac-halves:start.*?selftac-halves:end -->', lambda m: markup, src, flags=re.S)
    src, n2 = re.subn(r'var HALF_DX = [-\d.]+, HALF_DY = [-\d.]+;', f'var HALF_DX = {dx:.1f}, HALF_DY = {dy:.1f};', src)
    assert n1 == 1 and n2 == 1, (path, n1, n2)
    open(path, 'w').write(src)
    print('updated', os.path.relpath(path, D), f'dx={dx:.1f} dy={dy:.1f}')
