"""Write the Inside Out O sizing into both websites' wordmark CSS (see wordmark_metrics.py).

Main site: Newsreader 500 (Nacre) and Archivo 700 (Tidepool). Editorial: Newsreader 400 and Archivo 600.
The wordmark text is set at opsz 72 everywhere so its letters, and so the O, are the same drawing
at every size.
"""
import os, re
from wordmark_metrics import omark

D = os.path.dirname(os.path.abspath(__file__)) + '/'
INSIDE_OUT = (8, 9.5, 92, 93.5)
SITES = [(D + '../index.html', 'newsreader-500', 'archivo-700', '.bigmark, .giant'),
         (D + '../editorial/index.html', 'newsreader-400', 'archivo-600', '.brand .wm')]

def rule(sel, face):
    s, va, ml, mr = omark(INSIDE_OUT, face)
    return f'{sel} {{ width: {s:.4f}em; height: {s:.4f}em; vertical-align: {va:.4f}em; margin: 0 {mr:.4f}em 0 {ml:.4f}em; }}'

for path, serif, sans, words in SITES:
    src = open(path).read()
    css = ('/* wordmark:start (generated by brand/apply_wordmark.py) */\n'
           f'{words} {{ font-variation-settings: "opsz" 72; }}\n'
           '.om { display: inline-block; fill: currentColor; overflow: visible; }\n'
           + rule('.om', serif) + '\n' + rule(':root[data-palette="tidepool"] .om', sans) + '\n'
           '/* wordmark:end */')
    src, n = re.subn(r'/\* wordmark:start.*?/\* wordmark:end \*/', lambda m: css, src, flags=re.S)
    if not n:  # first run: replace the hand-written rules
        src, n = re.subn(r'\.om \{ display: inline-block; width: [^\n]*\n:root\[data-palette="tidepool"\] \.om \{[^\n]*\n', lambda m: css + '\n', src)
    assert n == 1, path
    open(path, 'w').write(src)
    print('updated', os.path.relpath(path, D))
